<?php
/**
 * @file
 *
 * @todo: Write description of file... what do it do.
 */

define('EZPROXY_AUTHENTICATION_URL', 'ezproxy_authentication');

/**
 * Implementation of hook_menu
 */
function ting_ezproxy_menu(){
  $items = array();

  $items['admin/settings/ting/ezproxy'] = array(
    'title' => 'Ezproxy settings',
    'description' => 'Configure EZProxy authenticaton',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_ezproxy_settings_form'),
    'file' => 'ting_ezproxy.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  $items[EZPROXY_AUTHENTICATION_URL] = array(
    'title' => 'Ezproxy callback',
    'description' => 'EZProxy menu callback to handle authentication',
    'page callback' => 'ting_ezproxy_handler',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * @todo: Missing description!.
 */
function ting_ezproxy_handler() {

  // Get url from ezproxy.
  $url = $_GET['url'];

  /**
   * @todo: Validate users input (url) is a url, valid_url($url) function maybe
   *        useful.
   */

  // We need a non-critical id on the user - actually uid can't be used - it's
  // not anonomous for public use.
  global $user;

  // Get config values.
  $config_values = variable_get('ting_ezproxy', array());

  if (user_is_anonymous()) {
    /**
     * @todo: Could drupal_set_message('you need to login to acccess...') with
     * drupal_goto('/user/login', array('destination' => EZPROXY_AUTHENTICATION_URL . '?url=' . $url));
     *
     * Might not work to the extra query string ?url ?.
     */
    $text = strtr($config_values['text_anonymous'], array(
      '@loginurl' => '/user/login?destination=' . EZPROXY_AUTHENTICATION_URL . '?url=' . $url,
      '@loginform' => drupal_get_form('user_login')
    ));
  }
  else {
    // User is now we are logged ind.
    $status = get_user_current_status($config_values['category'], $config_values['block']);

    if ($status) {
      // Blocked or other error.
      $text = $config_values['text_error'];
    }
    else if ( $status ) {
      // all okay - construct ticket

      $ezproxy  = new EZproxyTicket($config_values['domain'], $config_values['secret'], $user->uid, $config_values['citizen']);
      $text = strtr( $config_values['text_loggedin'], array('@tokenurl' => $ezproxy->url($url) ));
      drupal_set_html_head('<meta http-equiv="refresh" content="10;url=' . $ezproxy->url($url) . '">');

      /**
       * @todo: Chould drupal_goto() be used ? What does the 10; in content do ?
       */
    }
    else {
      // wrong category
      $text = $config_values['text_wrongcategory'];
    }
  }
  return $text;
}

/**
 * @todo: Missing description ?
 */
function get_user_current_status($category, $block) {
  global $user;

  if (user_is_anonymous()) {
    return FALSE;
  }

  $creds = ding_library_user_get_credentials($user);
  if ($creds != DING_PROVIDER_AUTH_REQUIRED) {
    // This need a update to AlmaClient.class.php with this line
    // 'category' =>  $info->getAttribute('patronCategory'),
    /**
    * @todo: Create pull request til alma module.
    */
    $user_data = alma_client_invoke('get_patron_info', $creds['user_id'], $creds['password'], TRUE);
  }

  // If no data? - then return null,
  if (!isset( $user_data["category"])) {
    return FALSE;
  }

  // Have the user some blocks then vi return FALSE if this... ?
  if ( isset($user_data["blocks"]) && ! empty($block) ) {
    $block_list = explode(',', $block);
    $regexp = '/(' . implode('|', preg_grep('/^\w+$/', $block_list)) . ')/';
    foreach ($user_data["blocks"] as $ele) {
      if (!$ele['is_system'] && preg_match($regexp , $ele['code'])) {
        return FALSE;
      }
    }
  }

  // Make the regexp with allowed categories and check this.
  $catlist = explode(',', $category);
  $regexp = '/(' . implode('|', preg_grep('/^\w+$/', $catlist)) . ')/';

  return preg_match ($regexp , $user_data["category"]);
}


/**
 * @todo: Missing description.
 *
 * @todo: Move class into own file and let autoloader load the class when
 * needed.
 *
 * From http://www.oclc.org/support/documentation/ezproxy/usr/ticket/php.htm
 */
class EZproxyTicket {
  var $EZproxyStartingPointURL;

  function EZproxyTicket($EZproxyServerURL, $secret, $user, $groups = "") {
    if (strcmp($secret, "") == 0) {
      echo("EZproxyURLInit secret cannot be blank");
      exit(1);
      /**
       * @todo: Use drupal_set_message and return FASLE and handle the error.
       *        this may give a WSOD. Never use exit, somebody might try to
       *        create the class and call the function.
       */
    }

    $packet = '$u' . time();
    if (strcmp($groups, "") != 0) {
      $packet .=  '$g' . $groups;
    }
    $packet .= '$e';
    $EZproxyTicket = urlencode(md5($secret . $user . $packet) . $packet);
    $this->EZproxyStartingPointURL = $EZproxyServerURL . "/login?user=" .
      urlencode($user) . "&ticket=" . $EZproxyTicket;
  }

  function url($url) {
    return $this->EZproxyStartingPointURL . "&url=" . $url;
  }
}
