<?php
/**
 * @file
 *
 * @todo: Write description of file... what do it do.
 */

define('EZPROXY_AUTHENTICATION_URL', 'ezproxy_authentication');

/**
 * Implementation of hook_menu
 */
function ting_ezproxy_menu(){
  $items = array();

  $items['admin/settings/ting/ezproxy'] = array(
    'title' => 'Ezproxy settings',
    'description' => 'Configure EZProxy authenticaton',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_ezproxy_settings_form'),
    'file' => 'ting_ezproxy.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 10,
  );

  $items[EZPROXY_AUTHENTICATION_URL] = array(
    'title' => 'Ezproxy callback',
    'description' => 'EZProxy menu callback to handle authentication',
    'page callback' => 'ting_ezproxy_handler',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * @todo: Missing description!.
 */
function ting_ezproxy_handler() {
  global $user;

  // Get config values.
  $config_values = variable_get('ting_ezproxy', array());

  if (user_is_anonymous()) {
    // Get text and replace token
    $text = strtr($config_values['text_anonymous'], array('@loginform' => drupal_get_form('user_login')));
  }
  else {
    // User is now logged in.
    $status = get_user_current_status($config_values['category'], $config_values['block']);

    if (is_null($status)) {
      // Blocked or other error.
      $text = $config_values['text_error'];
    }
    else if ($status) {
      // all okay - construct ticket

      // Get url from ezproxy
      // The content will be encoded in The Ezproxy-way eg. "ezp.2aH...s-"
      $url = $_GET['url'];
  
      // We should use a non-critical id on the user to the ezproxylog
      // @todo: do a MD5 hash on uid with some random number and save the connection uid/ezproxy_userid in watchdog
      $ezproxy_userid = $user->uid;

      // Make the ezproxy url with ticket
      $url_redirect  = make_ezproxy_url($config_values['domain'], $config_values['secret'], $ezproxy_userid, $config_values['citizen'], $url);

      $text = strtr( $config_values['text_loggedin'], array('@tokenurl' => $url_redirect ));

      $waittime = intval($config_values['loggedin_time']);
      if ( $waittime > 0 ) {
        drupal_set_html_head('<meta http-equiv="refresh" content="'. $waittime . ';url=' . $url_redirect . '">');
      }
      else if ( $waittime == 0 ) {
        drupal_goto($url_redirect);
      }
    }
    else {
      // wrong category
      $text = $config_values['text_wrongcategory'];
    }
  }
  return $text;
}

/**
 * @todo: Missing description ?
 */
function get_user_current_status($category, $block) {
  global $user;

  if (user_is_anonymous()) {
    return null;
  }

  $creds = ding_library_user_get_credentials($user);
  if ($creds != DING_PROVIDER_AUTH_REQUIRED) {
    // This need a update to AlmaClient.class.php with this line
    // 'category' =>  $info->getAttribute('patronCategory'),
    /**
    * @todo: Create pull request til alma module.
    */
    $user_data = alma_client_invoke('get_patron_info', $creds['user_id'], $creds['password'], TRUE);
  }

  // If no data? - then return null,
  if (!isset( $user_data["category"])) {
    return null;
  }

  // Have the user some blocks then vi return FALSE if this... ?
  if ( isset($user_data["blocks"]) && ! empty($block) ) {
    $block_list = explode(',', $block);
    $regexp = '/(' . implode('|', preg_grep('/^\w+$/', $block_list)) . ')/';
    foreach ($user_data["blocks"] as $ele) {
      if (!$ele['is_system'] && preg_match($regexp , $ele['code'])) {
        return null;
      }
    }
  }

  // Make the regexp with allowed categories and check this.
  $catlist = explode(',', $category);
  $regexp = '/(' . implode('|', preg_grep('/^\w+$/', $catlist)) . ')/';

  return preg_match ($regexp , $user_data["category"]);
}

/**
 * Make the Ezproxy-ticket
 *
 * From the documentation for Ezproxy
 * http://www.oclc.org/support/documentation/ezproxy/usr/ticket/php.htm
 */
function make_ezproxy_url($EZproxyServerURL, $secret, $user, $groups = "", $url) {
    $packet = '$u' . time();
    if (strcmp($groups, "") != 0) {
      $packet .=  '$g' . $groups;
    }
    $packet .= '$e';
    $EZproxyTicket = urlencode(md5($secret . $user . $packet) . $packet);
    return $EZproxyServerURL . "/login?user=" . urlencode($user) . "&ticket=" . $EZproxyTicket . "&qurl=" . urlencode($url);
}
